      - name: Fetch and parse OSRS world list
        id: parse
        run: |
          python - <<'EOF'
          import requests
          from bs4 import BeautifulSoup
          import pathlib
          import re, sys, os
          from datetime import datetime, timezone

          url = "https://oldschool.runescape.com/slu"
          resp = requests.get(url)
          resp.raise_for_status()

          soup = BeautifulSoup(resp.text, "lxml")

          seen = set()
          worlds = []

          for el in soup.find_all(string=True):
              text = el.strip()
              if text.startswith("Old School"):
                  cleaned = re.sub(r"\b\d+\s+players\b", "", text).strip()
                  cleaned = re.sub(r"^Old School\s+", "", cleaned)
                  if cleaned not in seen:
                      seen.add(cleaned)
                      worlds.append(cleaned)

          world_count = len(worlds)
          timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")

          if world_count == 0:
              print("ERROR: No worlds were found — parser likely broken.")
              sys.exit(1)

          def world_key(line: str):
              m = re.match(r"(\d+)", line)
              return int(m.group(1)) if m else 0

          worlds.sort(key=world_key)

          out_path = pathlib.Path("worlds.txt")
          out_path.write_text("\n".join(worlds) + "\n", encoding="utf-8")

          print(f"Wrote {world_count} unique, sorted worlds to {out_path} at {timestamp}")

          with open(os.environ["GITHUB_OUTPUT"], "a") as fh:
              print(f"world_count={world_count}", file=fh)
              print(f"timestamp={timestamp}", file=fh)
          EOF
