name: Update OSRS World List

on:
  schedule:
    - cron: "0 * * * *"   # once every hour
  workflow_dispatch:       # allow manual runs

jobs:
  update-worlds:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install requests beautifulsoup4 lxml

      - name: Fetch and parse OSRS world list
        id: parse
        run: |
          python - <<'EOF'
          import requests
          from bs4 import BeautifulSoup
          import pathlib
          import re
          from datetime import datetime
          import sys

          url = "https://oldschool.runescape.com/slu"
          resp = requests.get(url)
          resp.raise_for_status()

          soup = BeautifulSoup(resp.text, "lxml")

          seen = set()
          worlds = []

          # Look through all text nodes
          for el in soup.find_all(string=True):
              text = el.strip()
              if text.startswith("Old School"):
                  # Remove "### players"
                  cleaned = re.sub(r"\b\d+\s+players\b", "", text).strip()
                  # Drop "Old School " prefix
                  cleaned = re.sub(r"^Old School\s+", "", cleaned)
                  if cleaned not in seen:
                      seen.add(cleaned)
                      worlds.append(cleaned)

          world_count = len(worlds)
          timestamp = datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S UTC")

          if world_count == 0:
              print("ERROR: No worlds were found — parser likely broken.")
              sys.exit(1)

          # Sort numerically by world number
          def world_key(line: str):
              m = re.match(r"(\d+)", line)
              return int(m.group(1)) if m else 0

          worlds.sort(key=world_key)

          out_path = pathlib.Path("worlds.txt")
          out_path.write_text("\n".join(worlds) + "\n", encoding="utf-8")

          print(f"Wrote {world_count} unique, sorted worlds to {out_path} at {timestamp}")

          # GitHub Actions outputs
          print(f"::set-output name=world_count::{world_count}")
          print(f"::set-output name=timestamp::{timestamp}")
          EOF

      - name: Commit changes if needed
        run: |
          if git diff --quiet worlds.txt; then
            echo "No changes in worlds.txt"
          else
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add worlds.txt
            git commit -m "Update OSRS world list: ${{ steps.parse.outputs.world_count }} worlds @ ${{ steps.parse.outputs.timestamp }}"
            git push
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
